name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  RUST_TEST_THREADS: 1

jobs:
  test-windows:
    name: Windows (${{ matrix.target }})
    runs-on: windows-2019
    strategy:
      matrix:
        target:
          - i686-pc-windows-gnu
          - i686-pc-windows-msvc
          - x86_64-pc-windows-gnu
          - x86_64-pc-windows-msvc
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        target: ${{ matrix.target }}
        override: true

    - name: Run tests
      run: cargo test

  test-macos:
    name: macOS (x86_64-apple-darwin)
    runs-on: macos-10.15
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run tests
      run: cargo test

  test-linux:
    name: Linux (${{ matrix.target }})
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        target:
          - i686-unknown-linux-gnu
          - i686-unknown-linux-musl
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        target: ${{ matrix.target }}
        override: true

    - name: Run tests
      run: cargo test

  test-cross:
    name: Cross (${{ matrix.target }})
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        target:
          - armv7-unknown-linux-gnueabihf
          - aarch64-linux-android
          - mips-unknown-linux-gnu
          # - x86_64-unknown-freebsd
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        target: ${{ matrix.target }}
        override: true

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: test
        args: --target ${{ matrix.target }}

  check:
    name: Check (${{ matrix.target }})
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        target:
          - x86_64-unknown-illumos
          - x86_64-unknown-openbsd
          - x86_64-unknown-freebsd
      fail-fast: false

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        target: ${{ matrix.target }}
        override: true

    - name: Run check
      run: cargo check